### ISSUE TITLE
[Bug] Cables have no recipes.

### ISSUE THREAD

**Issue by Kevin-Marsh** [Technici4n/Modern-Dynamics#115]
The cables as can be seen [here](https://github.com/Technici4n/Modern-Dynamics/tree/0ea3c77cfdaa7fbd4f6d34a7837018561ed09a81/src/generated/resources/data/moderndynamics/recipe/cable) are all using the incorrect result formatting for 1.21 which means they have no recipe in game.
"item": "moderndynamics:ev_cable"
 "id": "moderndynamics:ev_cable"

**Comment by Technici4n** [comment]
Fixed by https://github.com/Technici4n/Modern-Dynamics/pull/116.
