### ISSUE TITLE
Is there a limit to inventory size pipes are pulling items out of?

### ISSUE THREAD

**Issue by EntityinArray** [Technici4n/Modern-Dynamics#118]
With large inventories (tom's storage mod connector) some items are not being pulled out of it.
In the screenshots below, you can see that Antimony Dust is not being pulled out of the Tom's Storage Mod network. Other items work fine.

Is there an inventory size limit, how many slots pipes will scan for desired item before giving up?
![image](https://github.com/user-attachments/assets/a92a12f3-b220-461c-9213-8be97863b88e)
![image](https://github.com/user-attachments/assets/aabb21ac-9bd6-4448-b77d-a8544edec719)
![image](https://github.com/user-attachments/assets/51307130-c922-4c70-a22f-2bc3cd8cca6a)

**Comment by Technici4n** [comment]
There is no limit coming from MD, but there might be a limit coming from Tom's.
