### ISSUE TITLE
Attachment that increases the speed of items traveling through it

### ISSUE THREAD

**Issue by Technici4n** [Technici4n/Modern-Dynamics#13]
`Accelerator`, probably.

**Comment by ProjectGSX** [comment]
This would be really fantastic.  Ive started getting into Fabric lately for the performance gains and the item pipes can barely keep up with a basic mob grinder only pulling out 4 items at a time.  Thanks for making this mod.

**Comment by Technici4n** [comment]
You can increase the amount of items pulled at once, and the pull frequency, using various upgrades.

To give you an idea of the supported upgrades: (**the effects can be seen by pressing U on an extractor in REI**)
![image](https://user-images.githubusercontent.com/13494793/186685522-81e56836-9e19-4c23-95ff-d74546ad3f42.png)
