### ISSUE TITLE
Server resets change extraction amounts.

### ISSUE THREAD

**Issue by Sidaithe** [Technici4n/Modern-Dynamics#31]
I have automatic restarts on my server which resets the item transfer amounts on the servos. Have to manually put them back to 64 each time. I mean I can stop the restarts but I imagine that shouldn't have to be the case.

Really enjoying the mod thus far though! Good work!

**Comment by Technici4n** [comment]
Hi, I can't reproduce this issue. Could you check that you tested with version 0.2.2-beta?

**Comment by Sidaithe** [comment]
Yes, tested with 0.2.2-beta.

**Comment by Technici4n** [comment]
Does this happen if you stop the server manually with `/stop`? I hope the auto-restart does not kill the process abruptly. :P

I only tried on singleplayer for now, but I don't see why it would only save on singleplayer and not on a server. Do you also have the issue if you join a singleplayer world?

**Comment by Sidaithe** [comment]
Still happens when stopping the server manually.

Does not happen in single player with the same mods so I doubt a mod conflict.

Only thing related to Modern Dynamics in my logs is:

"[22:45:34] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/minecraft/multicraft/servers/server1303131/default/jar/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[22:45:34] [main/INFO]: Compatibility level set to JAVA_16
[22:45:34] [main/INFO]: Compatibility level set to JAVA_17
[22:45:35] [main/WARN]: Reference map 'dual_riders-1.18.2-1.1.1-fabric-refmap.json' for dual_riders-fabric.mixins.json could not be read. If this is a development environment you can ignore this message
[22:45:35] [main/INFO]: Loaded configuration file for Lithium: 102 options available, 2 override(s) found
**[22:45:35] [main/WARN]: Reference map 'Modern-Dynamics-refmap.json' for moderndynamics.mixins.json could not be read. If this is a development environment you can ignore this message"**
