### ISSUE TITLE
[Crash] Server crashed on All of Fabric 5

### ISSUE THREAD

**Issue by SpigotDE** [Technici4n/Modern-Dynamics#32]
idk what happend , i woke up and server was stopped cause of crash 

[latest.log](https://gist.github.com/SpigotDE/20d9ef921b7560bcbf16f76e2db00339)
[crash-report](https://gist.github.com/SpigotDE/404a66a411cc532a02b6598b83d71ee2)

Modpack : [All of Fabric 5](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5)
Modpack Version : 1.3.0
1.18.2
Fabric 0.14.8

**Comment by Technici4n** [comment]
This sounds like an issue caused by mods loading and unloading chunks in parallel, maybe dynmap? I can't do anything about it unfortunately.
