### ISSUE TITLE
[1.19] Server crash after veinmining pipes

### ISSUE THREAD

**Issue by NyakoFox** [Technici4n/Modern-Dynamics#34]
Yesterday I tried to veinmine a bunch of pipes (system didn't end up working so I was tearing down the whole thing) which immediately lead to a server crash. Pure speculation, however I don't think the issue is with veinmining pipes specifically, but removing multiple pipes in a network on the same tick. Here's the [crash.txt](https://github.com/Technici4n/Modern-Dynamics/files/9151811/crash.txt).

**Comment by Technici4n** [comment]
I think the fix for #35 should also fix this.
