### ISSUE TITLE
[1.18.2] Upgrades not implemented?

### ISSUE THREAD

**Issue by MSandro** [Technici4n/Modern-Dynamics#36]
![image](https://user-images.githubusercontent.com/10937159/181287940-cbfe60fe-d879-4121-bf60-73c9e5fc13e9.png)
I don't understand how to upgrade the pipe. Eg. Items per Extraction, Speed, ...
or how to get the Advanced Behavior Upgrade?

**Comment by Technici4n** [comment]
Install REI and press U on a servo in your inventory to view the upgrades.

**Comment by MSandro** [comment]
great tyvm
