### ISSUE TITLE
Different Colored Pipes

### ISSUE THREAD

**Issue by Frankiscophil** [Technici4n/Modern-Dynamics#60]
Just a feature request for different colored pipes.

**Comment by Technici4n** [comment]
I don't see the point.

**Comment by Frankiscophil** [comment]
Mostly to differentiate pipes if one were to have a ton of them all with specific items going through them. It would be good to know which pipe system transported what items and so on.

**Comment by Frankiscophil** [comment]
Sorry, misclicked.

**Comment by Technici4n** [comment]
This is not planned, sorry. Vanilla doesn't allow you to color chests, for example. :wink:

I want to add facades eventually though.
