### ISSUE TITLE
I can't see pipes

### ISSUE THREAD

**Issue by McMonkey26** [Technici4n/Modern-Dynamics#61]
i'm not exactly sure what to put here. pipes are invisible. they exist, i can stand on them, i can use them, but they're completely invisible

mod list:
AdvancementPlaques-1.19.2-fabric-1.4.6.jar
architectury-6.4.62-fabric.jar
Bookshelf-Fabric01.19.2-16.2.16.jar
cloth-config-8.2.88-fabric.jar
daat-attributes-1.4.0.jar
EnchantmentDescriptions-Fabric-1.19.2-13.0.14.kar
fabric-api-0.72.0+1.19.2jar
fabric-quarry-1.19.2-1.0.3.jar
ForgeConfigAPIPort-v4.2.10-1.19.2-Fabric.jar
Iceberg-1.19.1-fabric-1.0.46.jar
ItemBorders-1.19-fabric-1.1.6.jar
Jade-1.19.1-fabric-8.7.3.jar
journeymap-1.19.2-5.9.2-fabric.jar
JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar
lambdynamiclights-2.1.2+1.19.jar
LegendaryTooltips-1.19.2-fabric-1.3.3.jar
lithium-fabric-mc1.19.2-0.10.4.jar
Mekanism-1.19.2-10.3.5.473.jar
MerchantMarkers-1.19.1-fabric-1.2.3.jar
Modern-Dynamics-0.3.3-beta.jar
Patchouli-1.19.2-77-FABRIC.jar
phosphor-fabric-mc1.19.x-0.8.1.jar
playerex-3.5.0.jar
Prism-1.19.2-fabric-1.0.3.jar
PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
RebornCore-5.4.0.jar
repurposed_structures_quilt-6.3.9+1.19.2.jar
RoughlyEnoughItems-9.1.587.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
TechReborn-5.4.0.jar
Torcherino-fabric-1.19-17.0.1.jar
TravelersTitles-1.19.2-Fabric-3.1.0.jar
VisualWorkbench-v4.2.1-1.19.2-Fabric.jar
YungsApi-1.19.2-Fabric-3.8.2.jar
YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar
YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0.jar
YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar
YungsBridges-1.19.2-Fabric-3.1.0.jar
YungsExtras-1.19.2-Fabric-3.1.0.jar

**Comment by Technici4n** [comment]
Install indium.
