### ISSUE TITLE
Excessive amount of item transfer will lead to client connection failure

### ISSUE THREAD

**Issue by aria1th** [Technici4n/Modern-Dynamics#65]
Mods like https://github.com/AztechMC/Modern-Industrialization requires tremendous amount of item transfer (with visualization).
But, basically packets from item transport will bottleneck client network connection, and will lead to client connection failure (TCP Reset).

We need packet limit config per network to prevent those cases.

**Comment by Technici4n** [comment]
Hi, can you provide a client profile (`/sparkc`) so I can see what's so slow with the client's handling?

**Comment by aria1th** [comment]
https://spark.lucko.me/TT7qG2MwWo
Here is it, I reduced amount of transfer until It was 'okay'

**Comment by aria1th** [comment]
Also I observed significant lag on server side, here is server report:
https://spark.lucko.me/9KsUS0g25m

**Comment by Technici4n** [comment]
Oh damn, TR storage units strike again... :/

**Comment by aria1th** [comment]
In fact, I reduced its packet amount to 1/20 and it was laggy too..., but with modern dynamic's pipe, I can confirm it was sending 2700 packet / second

**Comment by Technici4n** [comment]
Server side needs optimizations on TR's end. Client side is very easy to fix for me, the pipes are recomputing their shape needlessly and that's very expensive. Should be fixed this week.

**Comment by Technici4n** [comment]
I just released version 0.4.1-beta (will be out in a few minutes), let me know if that helps with the issue on the client side.
