### ISSUE TITLE
Extrators and upgrades gone after update to 0 4 2 on 1 19 2

### ISSUE THREAD

**Issue by Night-Sky1970** [Technici4n/Modern-Dynamics#67]
no error msg nothing.. there just gone after the update :)

however pipes are now at once piece instead of lill cubes so that part you got fixed.. :)

thank you for youre time and the work you put in youre lovely mod :)

Monique

**Comment by Technici4n** [comment]
Hi, that should be fixed in 0.4.3, sorry about that. 😅
