### ISSUE TITLE
Empty whitelists allow all items

### ISSUE THREAD

**Issue by Qendolin** [Technici4n/Modern-Dynamics#7]
An empty whitelist in a servo, etc. will allow all items to pass.

**Comment by Technici4n** [comment]
That's "by design", that's also how AE2 works, but I am open to changing it.

**Comment by Technici4n** [comment]
I think the idea is that whitelisting an item only takes one click on a filter slot instead of two (one on a filter slot, then one to change from blacklist to whitelist). We could also default to an empty whitelist but that might be a bit annoying?

**Comment by Qendolin** [comment]
I thought I remembered TD having blacklist set as the default but I didn't check 😓. But yeah maybe that's a behavior worth discussing since it is a bit unintuitive.

**Comment by Qendolin** [comment]
I just checked on the 1.12.2 version of Thermal Dynamics and it uses blacklist as the default.
