### ISSUE TITLE
Transporting from p2p tunnel - me into terminal

### ISSUE THREAD

**Issue by EpsilonCZZ** [Technici4n/Modern-Dynamics#85]
Hello, recently i have problem with drives are not transporting items with P2P tunnel - ME.
I did this setup multiple times, but never had problem with this.
Everything has good frequency, everything is giving channels, but from other then cables right next to drivers i cant see items. I cant see craftable items not even from moleculars assemblers. 
Thanks for every tip. 
![ef62a0fb-4e54-401b-98f5-46d38711a031](https://github.com/Technici4n/Modern-Dynamics/assets/157517773/de1ed65e-0b33-4c54-b0db-3306aa900c35)
![37013bd3-95dd-403f-82e8-1da07f86aa7b](https://github.com/Technici4n/Modern-Dynamics/assets/157517773/45c0740a-0024-4029-933c-bc82daf4d9b4)
![8b466da9-7a79-459b-81b1-3155d9cf67c1](https://github.com/Technici4n/Modern-Dynamics/assets/157517773/4949d629-c086-4d9f-8f14-efa7b1ed730a)

**Comment by 62832** [comment]
This isn't the Applied Energistics repo.

**Comment by EpsilonCZZ** [comment]
crap
