### ISSUE TITLE
[1.20.1] Energy cables not connecting or tranfering power

### ISSUE THREAD

**Issue by BillBodkin** [Technici4n/Modern-Dynamics#86]
While the cables do connect to each over, they do not connect to block form other mods that use TechReborn energy API.
Tested with 'Create Crafts and Add-ons' Mod.

**Comment by Technici4n** [comment]
Yes, they are cables specifically designed to work with Modern Industrialization. :wink:

**Comment by BillBodkin** [comment]
Ah ok, im currently making a mod that uses https://github.com/TechReborn/Energy which had the same issue, but could be powered by Create Crafts and Add-ons.

Does Modern Industrialization use a different energy system?

**Comment by ramidzkh** [comment]
Yes, but there is a config option in MI to enable compat with TR energy
